### PR TITLE
Fix issues with overlap

### PR DESCRIPTION
**Pull request by mario**
Signed-off-by: Mario Danic <mario@lovelyhq.com>

### CODE REVIEW

**Comment by chris6647** [comment]
Could you give me some more information as to the issue this fixes? Along with steps to reproduce the issue it fixes. I just see that you move some of the setup into onAttach instead, and the commit message just mentions something with overlap.

**Comment by mario** [comment]
Of course. Since onViewBound is invoked only once, there's the following problem:

- start another activity
- go back
- lastActiveChildRouter will be null
- therefore new controller would be created  causing UI overlap (one controller on top of another)
- also clicking back button would crash hard since lastActiveChildRouter doesn't exist :)

**Comment by chris6647** [comment]
Turns out that we actually had the same issue (just still within a single activity) in our backlog, and this does indeed fix it :) Thanks!

**Comment by mario** [comment]
Awesome! Glad I was of help! If you'd at any point like to know where your work is used, let me know and I'll point you to it! :)

**Pull request merged**
